---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: auth
          image: clrosier/auth:latest
          env:
            - name: AUTH_DB_URL
              value: "localhost"
            - name: AUTH_DB_USER
              value: auth
            - name: AUTH_DB_PASS
              value: apple321
            - name: AUTH_DB_PORT
              value: 32541
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    service: auth
spec:
  selector:
    app: auth
  ports:
    - port: 5000
      targetPort: 5000
            