---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: auth
          image: clrosier/auth:latest
          env:
            - name: AUTH_DB_URL
              value:
            - name: AUTH_DB_USER
              value: auth
            - name: AUTH_DB_PASS
              value: apple321
            - name: AUTH_DB_PORT
              value: 32541
    restartPolicy: Always
            