---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: clrosier/auth:arm64-1.0.8
          env:
          - name: AUTH_DB_URL
            value: 192.168.0.183
          - name: AUTH_DB_USER
            valueFrom:
              secretKeyRef:
                key: db_user
                name: db-user-cred
          - name: AUTH_DB_PASS
            valueFrom:
              secretKeyRef:
                key: db_pass
                name: db-user-cred
          - name: AUTH_DB_PORT
            value: "32511"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    service: auth
spec:
  selector:
    app: auth
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: auth
              servicePort: 5000